const TournamentData = [
    {
        id: 1,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "01:30 PM",
        status:"FULL",
        players : "90",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "5000",
        entryFees : "50",
        weeklyTournament : false,
        type : "current",
        date : "11"
    },
    {
        id: 89,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:30 PM",
        status:"JOIN",
        players : "37",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "4000",
        entryFees : "40",
        weeklyTournament : false,
        type : "current",
        date : "11",
    },
    {
        id: 2,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "01:30 PM",
        status:"FULL",
        players : "90",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "5000",
        entryFees : "50",
        weeklyTournament : false,
        type : "current",
        date : "11"
    },
    {
        id: 3,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:00 PM",
        status:"JOINED",
        players : "72",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SQUAD",
        prizeMoney : "10000",
        entryFees : "100",
        weeklyTournament : false,
        type : "current",
        date : "11",
        room : {
            status : true,
            available : false,
            roomId : "",
            password : ""
        }
    },
    {
        id: 4,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:00 PM",
        status:"JOINED",
        players : "72",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "10000",
        entryFees : "100",
        weeklyTournament : false,
        type : "current",
        date : "11",
        room : {
            status : true,
            available : true,
            roomId : "991004550",
            password : "nk0019453"
        }
    },
    {
        id: 5,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:30 PM",
        status:"JOIN",
        players : "37",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "4000",
        entryFees : "40",
        weeklyTournament : false,
        type : "current",
        date : "16",

    },
    {
        id: 6,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:30 PM",
        status:"JOIN",
        players : "37",
        capacity : "100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "4000",
        entryFees : "40",
        weeklyTournament : false,
        type : "current",
        date : "13",
    },

];

const PastTournamentData = [

    {
        id: 1,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "01:30 PM",
        status:"RESULT",
        players : "90/100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "5000",
        entryFees : "50",
        weeklyTournament : false,
        type : "past",
        cashWon : "10",
        rank : "8",
        totalWinners : "30",
        date : "OCT, 07 2021",
        kill : 0
    },
    {
        id: 2,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:00 PM",
        status:"RESULT",
        players : "72/100",
        map : "ERANGLE",
        teamType : "SQUAD",
        prizeMoney : "10000",
        entryFees : "100",
        weeklyTournament : false,
        type : "past",
        cashWon : "10",
        rank : "2",
        totalWinners : "30",
        date : "OCT, 07 2021",
        kill : 2
    },
    {
        id: 3,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/banner/pubg-thum1.jpg',
        time : "02:30 PM",
        status:"RESULT",
        players : "37/100",
        map : "ERANGLE",
        teamType : "SOLO",
        prizeMoney : "4000",
        entryFees : "40",
        weeklyTournament : false,
        type : "past",
        cashWon : "10",
        rank : "1",
        totalWinners : "30",
        date : "OCT, 07 2021",
        kill : 5
    },
];

const TournamentResultData = [
    {
        id: 1,
        image:'https://res.mobibattle.co/Demo/images/avatar/user3.png',
        rank : "#1",
        kills:"5",
        prize : "40",
        battleName : "BNGMOBILE",
    },
    {
        id: 2,
        image:'https://res.mobibattle.co/Demo/images/avatar/user4.png',
        rank : "#2",
        kills:"2",
        prize : "10",
        battleName : "BNGMOBILE",
    },
    {
        id: 3,
        image:'https://res.mobibattle.co/Demo/images/avatar/user5.png',
        rank : "#3",
        kills:"1",
        prize : "5",
        battleName : "BNGMOBILE",
    },
    {
        id: 4,
        image:'https://res.mobibattle.co/Demo/images/avatar/user6.png',
        rank : "#4",
        kills:"0",
        prize : "0",
        battleName : "BNGMOBILE",
    },
    {
        id: 5,
        image:'https://res.mobibattle.co/Demo/images/avatar/user7.png',
        rank : "#5",
        kills:"0",
        prize : "0",
        battleName : "BNGMOBILE",
    },
    {
        id: 6,
        image:'https://res.mobibattle.co/Demo/images/avatar/user8.png',
        rank : "#6",
        kills:"0",
        prize : "0",
        battleName : "BNGMOBILE",
    },
];

const TournamentHomeData = [
    {
        id: 1,
        image:'https://res.mobibattle.co/Demo/tournament/pubg/league/pubg-thum-h1.jpg',
        won : "150000",
        upcomingMatches:"45",
        totolMatchesPlayed : "510",
    },
    {
        id: 2,
        image:'https://res.mobibattle.co/Demo/tournament/free-fire/league/free-fire-h3.jpg',
        won : "150000",
        upcomingMatches:"45",
        totolMatchesPlayed : "510",
    },

];

const TournamentDates = [
    { id: 1, date: "11", day: "Mon" },
    { id: 2, date: "12", day: "Tue" },
    { id: 3, date: "13", day: "Wed" },
    { id: 4, date: "14", day: "Thu" },
    { id: 5, date: "15", day: "Fri" },
    { id: 6, date: "16", day: "Sat" },
    { id: 7, date: "17", day: "Sun" },
    { id: 8, date: "18", day: "Mon" },
    { id: 9, date: "19", day: "Tue" },
]

export { TournamentData, PastTournamentData, TournamentResultData, TournamentHomeData, TournamentDates};
