export const events = {
    open: "open",
    apiRequestMade: "apiRequestMade",
    apiSuccess: "apiSuccess",
    apiFailure: "apiFailure",
    gameClick: "gameClick",
    bannerClick: "bannerClick",
    trendingClick: "trendingClick",
    walletClick: "walletClick",
    profileClick: "profileClick",
    sideMenuClick: "sideMenuClick",
    homeClick: "homeClick",
    freeClick: "freeClick",
    fiveClick: "fiveClick",
    tenClick: "tenClick",
    fifteenClick: "fifteenClick",
    playGameApiSuccess: "playGameApiSuccess",
    playGameApiFailure: "playGameApiFailure",
    premiumClicked: "premiumClicked",
    becomePremiumClicked: "becomePremiumClicked",
    backButton: "backButton",
    gameRules: "gameRules",
    leaveGame: "leaveGame",
    keepPlaying: "keepPlaying",
    gameStart: "gameStart",
    gameEnd: "gameEnd",
    sendFindBattle: "sendFindBattle",
    matchFound: "matchFound",
    opponentOut: "opponentOut",
    callBot: "callBot",
    // dis - socketDisconnect
    dis: "dis",
    endBattle: "endBattle",
    startBattle: "startBattle",
    endData: "endData",
    addMoneyClick: "addMoneyClick",
    gameInit: "gameInit",
    playAgainClick: "playAgainClick",
    leaderboardClick: "leaderboardClick",
    claimNowClicked: "claimNowClicked",
    claimApiSuccess: "claimApiSuccess",
    claimApiFailure: "claimApiFailure",
    playNow: "playNow",
    registerApiSuccess: "registerApiSuccess",
    registerApiFailure: "registerApiFailure",
    balanceApiSuccess: "balanceApiSuccess",
    balanceApiFailure: "balanceApiFailure",
    avatarApiSuccess: "avatarApiSuccess",
    avatarApiFailure: "avatarApiFailure",
    createProfileApiSuccess: "createProfileApiSuccess",
    createProfileApiFailure: "createProfileApiFailure",
    cancelClick: "cancelClick",
    mojiClick: "mojiClick",
    claimNowClick: "claimNowClick",
    closed: "closed",
    click: "click",
    sendOtpApiSuccess: "sendOtpApiSuccess",
    sendOtpApiFailure: "sendOtpApiFailure",
    subscriptionApiSuccess: "subscriptionApiSuccess",
    subscriptionApiFailure: "subscriptionApiFailure",
    tournamentListApiSuccess: "tournamentListApiSuccess",
    tournamentListApiFailure: "tournamentListApiFailure",
    viewMatches: "viewMatches",
    viewAll: "viewAll",
    tournamentRulesClick: "tournamentRulesClick",
    pastTournamentClick: "pastTournamentClick",
    editUserNameClick: "editUserNameClick",
    saveButtonClick: "saveButtonClick",
    addGameIdApiSuccess: "addGameIdApiSuccess",
    addGameIdApiFailure: "addGameIdApiFailure",
    calenderBtnClick: "calenderBtnClick",
    tournamentCardPrizeBtnClick: "tournamentCardPrizeBtnClick",
    joinTournamentApiSuccess: "joinTournamentApiSuccess",
    joinTournamentApiFailure: "joinTournamentApiFailure",
    conformationApiSuccess: "conformationApiSuccess",
    conformationApiFailure: "conformationApiFailure",
    RESULT: "RESULT",
    JOIN: "JOIN",
    okayClicked: "okayClicked",
    roomIdCopy: "roomIdCopy",
    passwordCopy: "passwordCopy",
    continueBtnClick: "continueBtnClick",
    gameDetailsApiSuccess: "gameDetailsApiSuccess",
    gameDetailsApiFail: "gameDetailsApiFail"
}



export const screen = {
    home_p: "home_p",
    home_p_balance: "home_p_balance",
    gameDetails_p: "gameDetails_p",
    game_p: "game_p",
    dev_s: "dev_s",
    gameResult_p: "gameResult_p",
    scratchCard: "scratchCard",
    landing_p: "landing_p",
    login_p: "login_p",
    otp_p: "otp_p",
    header: "header",
    wallet_p: "wallet_p",
    moji_p: "moji_p",
    myProfile_p: "myProfile_p",
    transaction_p: "transaction_p",
    leaderBoard_p: "leaderBoard_p",
    gameHistory_p: "gameHistory_p",
    // tournament
    tournamentHistory_p: "tournamentHistory_p",
    tournamentList_p: "tournamentList_p",
    tournamentUserName_p: "tournamentUserName_p",
    prizePool_p: "prizePool_p",
    subscription_p: "subscription_p",
    withdraw_p : "withdraw_p",
    buyCoin_p : "buyCoin_p"
}



